---
services:
  mochad-mqtt-bridge:
    extends:
      file: docker-compose.yml
      service: mochad-mqtt-bridge
    environment:
      MQTT_PASSWORD:
      MQTT_PASSWORD_FILE: /run/secrets/mqtt_password
      MQTT_TLS_ENABLED: ${MQTT_TLS_ENABLED:-true}
      MQTT_TLS_CA_FILE: /run/secrets/mqtt_ca
      MQTT_TLS_CERT_FILE: /run/secrets/mqtt_client_cert
      MQTT_TLS_KEY_FILE: /run/secrets/mqtt_client_key
      MQTT_TLS_KEY_PASSWORD:
      MQTT_TLS_KEY_PASSWORD_FILE: /run/secrets/mqtt_client_key_password
    secrets:
      - mqtt_password
      - mqtt_ca
      - mqtt_client_cert
      - mqtt_client_key
      - mqtt_client_key_password

secrets:
  mqtt_password:
    file: ./secrets/mqtt_password.txt
  mqtt_ca:
    file: ./secrets/mqtt_ca.crt
  mqtt_client_cert:
    file: ./secrets/mqtt_client.crt
  mqtt_client_key:
    file: ./secrets/mqtt_client.key
  mqtt_client_key_password:
    file: ./secrets/mqtt_client_key_password.txt
